/*
 * Pseudo-code: File routeTree.gen.ts defines the routeTree.gen component/module.
 * Why added: Added to provide pseudo-code documentation for the CI/CD portfolio.
 */

/*
 * Pseudo-code: File routeTree.gen.ts defines the routeTree.gen component/module.
 * Why added: Added to provide pseudo-code documentation for the CI/CD portfolio.
 */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const TechstackLazyRouteImport = createFileRoute('/techstack')()
const ProjectLazyRouteImport = createFileRoute('/project')()
const ContactLazyRouteImport = createFileRoute('/contact')()
const IndexLazyRouteImport = createFileRoute('/')()

const TechstackLazyRoute = TechstackLazyRouteImport.update({
  id: '/techstack',
  path: '/techstack',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/techstack.lazy').then((d) => d.Route))
const ProjectLazyRoute = ProjectLazyRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/project.lazy').then((d) => d.Route))
const ContactLazyRoute = ContactLazyRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRoute
  '/project': typeof ProjectLazyRoute
  '/techstack': typeof TechstackLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRoute
  '/project': typeof ProjectLazyRoute
  '/techstack': typeof TechstackLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/contact': typeof ContactLazyRoute
  '/project': typeof ProjectLazyRoute
  '/techstack': typeof TechstackLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/project' | '/techstack'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/project' | '/techstack'
  id: '__root__' | '/' | '/contact' | '/project' | '/techstack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ContactLazyRoute: typeof ContactLazyRoute
  ProjectLazyRoute: typeof ProjectLazyRoute
  TechstackLazyRoute: typeof TechstackLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/techstack': {
      id: '/techstack'
      path: '/techstack'
      fullPath: '/techstack'
      preLoaderRoute: typeof TechstackLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ContactLazyRoute: ContactLazyRoute,
  ProjectLazyRoute: ProjectLazyRoute,
  TechstackLazyRoute: TechstackLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
